import * as admin from 'firebase-admin';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { logger } from 'firebase-functions/v2';
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { REGION } from './region';

if (admin.apps.length === 0) {
  admin.initializeApp();
}

const REPORT_TYPES = ['monthlySummary', 'categoryDetail', 'volunteerPerformance'];

interface ValidatedPayload {
  report_type: string;
  period_start: number; // epoch millis
  period_end: number; // epoch millis
}

// Server re-validation, same convention as create_donation_report.ts.
function validate(payload: unknown): ValidatedPayload {
  if (typeof payload !== 'object' || payload === null) {
    throw new HttpsError('invalid-argument', 'Malformed request.', {
      code: 'VALIDATION_FAILED',
    });
  }
  const p = payload as Record<string, unknown>;

  if (typeof p.report_type !== 'string' || !REPORT_TYPES.includes(p.report_type)) {
    throw new HttpsError('invalid-argument', 'Invalid report_type.', {
      code: 'VALIDATION_FAILED',
    });
  }
  if (typeof p.period_start !== 'number' || !Number.isFinite(p.period_start)) {
    throw new HttpsError('invalid-argument', 'Invalid period_start.', {
      code: 'VALIDATION_FAILED',
    });
  }
  if (
    typeof p.period_end !== 'number' ||
    !Number.isFinite(p.period_end) ||
    p.period_end <= p.period_start
  ) {
    throw new HttpsError('invalid-argument', 'Invalid period_end.', {
      code: 'VALIDATION_FAILED',
    });
  }

  return {
    report_type: p.report_type,
    period_start: p.period_start,
    period_end: p.period_end,
  };
}

// Report generation (FR12, Screen 12 export). Aggregates DonationReports
// server-side and persists a Reports doc (Table 4.8) — firestore.rules
// denies direct client writes on Reports, so this callable is the only
// write path (mirrors createDonationReport's callable-only convention).
//
// Governing filter (resolved Figure 5.9-prose vs Table 4.8-field-semantics
// conflict — see memory/project_alkhair_phase6.md and monthly_summary.dart):
// only status == 'delivered' reports within [period_start, period_end)
// count toward total_donations/total_quantity.
export const generateReport = onCall({ region: REGION }, async (request) => {
  const uid = request.auth?.uid;
  if (!uid || request.auth?.token.role !== 'charity_admin') {
    throw new HttpsError('permission-denied', 'Only charity admins may generate reports.');
  }

  const data = validate(request.data);
  const db = admin.firestore();

  const adminSnap = await db.doc(`CharityAdmins/${uid}`).get();
  const charityId = adminSnap.data()?.charity_id as string | undefined;
  if (!charityId) {
    throw new HttpsError('permission-denied', 'No charity_id on admin profile.');
  }

  // Single-charity MVP: DonationReports carries no charity_id (see Phase 5
  // scoping note) — aggregation covers all delivered reports in the window.
  const snap = await db
    .collection('DonationReports')
    .where('status', '==', 'delivered')
    .where('created_at', '>=', Timestamp.fromMillis(data.period_start))
    .where('created_at', '<', Timestamp.fromMillis(data.period_end))
    .get();

  let totalQuantity = 0;
  for (const doc of snap.docs) {
    totalQuantity += (doc.data().quantity as number) ?? 0;
  }
  const totalDonations = snap.size;

  const reportRef = db.collection('Reports').doc();
  const generatedAt = FieldValue.serverTimestamp();

  await reportRef.set({
    report_id: reportRef.id,
    charity_id: charityId,
    generated_by: uid,
    report_type: data.report_type,
    period_start: Timestamp.fromMillis(data.period_start),
    period_end: Timestamp.fromMillis(data.period_end),
    total_donations: totalDonations,
    total_quantity: totalQuantity,
    generated_at: generatedAt,
  });

  logger.info(`Reports doc generated by ${uid}`, { report_id: reportRef.id });

  const written = await reportRef.get();
  const writtenGeneratedAt = written.get('generated_at') as Timestamp;

  return {
    report_id: reportRef.id,
    charity_id: charityId,
    generated_by: uid,
    report_type: data.report_type,
    period_start: data.period_start,
    period_end: data.period_end,
    total_donations: totalDonations,
    total_quantity: totalQuantity,
    generated_at: writtenGeneratedAt.toMillis(),
  };
});
