// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe5-EZPP0QSASMawhjybQW4u5ARtFinmg',
    appId: '1:607618058479:web:65729ec66379b44d49731a',
    messagingSenderId: '607618058479',
    projectId: 'alkhair-bisha-dev',
    authDomain: 'alkhair-bisha-dev.firebaseapp.com',
    storageBucket: 'alkhair-bisha-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIA1x5QhNWu79oefFwFbN-V7lTqmlZlHs',
    appId: '1:607618058479:android:ef6a5c263557a48649731a',
    messagingSenderId: '607618058479',
    projectId: 'alkhair-bisha-dev',
    storageBucket: 'alkhair-bisha-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49FHvWTBkE8LXaQeDc-G_WcZ71_Cr-08',
    appId: '1:607618058479:ios:a935c5d72f28ea1a49731a',
    messagingSenderId: '607618058479',
    projectId: 'alkhair-bisha-dev',
    storageBucket: 'alkhair-bisha-dev.firebasestorage.app',
    iosBundleId: 'com.alkhair.alkhairApp',
  );
}
